blueprint:
  name: Bi-Directional Switch
  description: |
    VDBX FLIP Shift - 4x Bidrectional Switch Panel presents four Text Sensors, import this into Home Assistant and create a new automation for each switch.
    TODO: Needs Left/Right triggers
  domain: automation
  input:
    text_sensor_id:
      name: Text Sensor for Switch
      description: The text sensor used to trigger the automation
      selector:
        entity:
          filter:
            - integration: esphome
              domain: sensor
              #device_class: enum
    up_act:
      name: Up Single action
      description: The action(s) to launch for a single up click
      default: []
      selector:
        action: {}
    down_act:
      name: Down Single click action
      description: The action(s) to launch for a single down click
      default: []
      selector:
        action: {}
    dbl_up_act:
      name: Double Up action
      description: The action(s) to launch for a double up click
      default: []
      selector:
        action: {}
    dbl_down_act:
      name: Double Down click action
      description: The action(s) to launch for a double down click
      default: []
      selector:
        action: {}
    hold_up_act:
      name: Hold Up action
      description: The action(s) to launch for a hold up
      default: []
      selector:
        action: {}
    hold_down_act:
      name: Hold Down action
      description: The action(s) to launch for a hold down
      default: []
      selector:
        action: {}
    
    
  #source_url: https://gist.github.com/agdamsbo/f49277bd8dd9bbada055c49600bea9e2
trigger:
- platform: state
  entity_id: !input 'text_sensor_id'
  to: 'Up'
- platform: state
  entity_id: !input 'text_sensor_id'
  to: 'Down'
- platform: state
  entity_id: !input 'text_sensor_id'
  to: 'Double Up'
- platform: state
  entity_id: !input 'text_sensor_id'
  to: 'Double Down'
- platform: state
  entity_id: !input 'text_sensor_id'
  to: 'Hold Up'
- platform: state
  entity_id: !input 'text_sensor_id'
  to: 'Hold Down'
action:
- choose:
  - conditions:
    - condition: state
      entity_id: !input 'text_sensor_id'
      state: 'Up'
    sequence: !input 'up_act'
  - conditions:
    - condition: state
      entity_id: !input 'text_sensor_id'
      state: 'Down'
    sequence: !input 'down_act'
  - conditions:
    - condition: state
      entity_id: !input 'text_sensor_id'
      state: 'Double Up'
    sequence: !input 'dbl_up_act'
  - conditions:
    - condition: state
      entity_id: !input 'text_sensor_id'
      state: 'Double Down'
    sequence: !input 'dbl_down_act'
  - conditions:
    - condition: state
      entity_id: !input 'text_sensor_id'
      state: 'Hold Up'
    sequence: !input 'hold_up_act'
  - conditions:
    - condition: state
      entity_id: !input 'text_sensor_id'
      state: 'Hold Down'
    sequence: !input 'hold_down_act'