esphome:
  name: genmod-mini-ae56482
  

esp8266:
  board: esp01_1m
  restore_from_flash: true

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "21c860225999f4f2cc71b515c5726f3c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Genmod-Mini-Ae56482"
    password: "qKO1ioIjiz9W"

captive_portal:


globals:
  - id: genHours
    type: float
    restore_value: yes
    
    
    
#While input X on then increment genMins every 60 seconds
interval:
  - interval: 1min
    then:
      - lambda: |-
         id(genHours) += 0.016666; 
         id(generator_hours).publish_state(id(genHours));
         ESP_LOGD("main", "Generator Hours: %.1f", id(genHours));
        

  
number:
  - platform: template
    name: "Generator Hours - Mini"
    id: generator_hours
    optimistic: true
    min_value: 0
    max_value: 10000
    step: 0.01

    