substitutions:
  name: flip-c3-00cca4
  friendly_name: FLIP-C3 00cca4
packages:
  vdbxio.FLIP-C3: github://vdbxio/wiki/esphome/flip-c3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: VDEDIcqV3WlcZTQzXhpyO1J50fL8cbqyP3AFFNnOhx4=
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
